name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build and deploy
      env:
        MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
      run: |
        echo "<!DOCTYPE html>
        <html>
        <head>
            <title>Google Maps Visualization</title>
            <style>
                #map {
                    height: 100%;
                }
                html, body {
                    height: 100%;
                    margin: 0;
                    padding: 0;
                }
            </style>
            <script>
                const MAPS_API_KEY = '${MAPS_API_KEY}';
                function initMap() {
                    fetch('cleaned_data.csv')
                    .then(response => response.text())
                    .then(data => {
                        const rows = data.split('\n').slice(1);
                        const map = new google.maps.Map(document.getElementById('map'), {
                            zoom: 4,
                            center: { lat: 39.8283, lng: -98.5795 }
                        });
                        rows.forEach(row => {
                            const cols = row.split(',');
                            const lat = parseFloat(cols[2]);
                            const lng = parseFloat(cols[3]);
                            const datetime = cols[0];
                            const duration = cols[1];
                            new google.maps.Marker({
                                position: { lat, lng },
                                map,
                                title: `Time: ${datetime}, Duration: ${duration}`
                            });
                        });
                    });
                }
            </script>
        </head>
        <body>
            <div id='map'></div>
            <script src='https://maps.googleapis.com/maps/api/js?key=${MAPS_API_KEY}&callback=initMap' async defer></script>
        </body>
        </html>" > index.html

        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add index.html
        git commit -m "Deploy to GitHub Pages"
        git push origin main
